F_DATASET_COLUMNS = [
    'fire_id',
    'discovery_date',
    'discovery_time',
    'month',
    'day_of_year',
    'latitude',
    'longitude',
    'state',
    'elevation',
    'fire_size',
    'fire_class',
    'general_cause',
    'origin',
    't_max',
    't_min',
    'temp_range',
    't_max_prev_7day_avg',
    't_min_prev_7day_avg',
    'temp_category',
    'fire_size_category',
    'is_weekend',
    'season',
    'state_avg_temp',
    'state_fire_frequency'
]

F_DATASET_COLUMNS_DICTIONARY = {
    'fire_id': 'Unique identifier for each fire event',
    'discovery_date': 'Date of fire discovery (YYYY-MM-DD)',
    'discovery_time': 'Time of fire discovery (HH:MM)',
    'month': 'Month extracted from discovery date (1-12)',
    'day_of_year': 'Day of year extracted from discovery date (1-365/366)',
    'latitude': 'Latitude of the fire',
    'longitude': 'Longitude of the fire',
    'state': 'State abbreviation (e.g., CA, TX)',
    'elevation': 'Elevation from weather data',
    'fire_size': 'Size of the fire',
    'fire_class': 'Classification of fire size (A, B, C, etc.)',
    'general_cause': 'Cause of the fire',
    'origin': 'Origin of the fire (e.g., Natural, Accidental)',
    't_max': 'Maximum temperature on the day of discovery',
    't_min': 'Minimum temperature on the day of discovery',
    'temp_range': 'Calculated as t_max - t_min',
    't_max_prev_7day_avg': 'Average maximum temperature for the 7 days prior to the fire',
    't_min_prev_7day_avg': 'Average minimum temperature for the 7 days prior to the fire',
    'temp_category': 'Categorized temperature (e.g., Cool, Mild, Hot, Extreme)',
    'fire_size_category': 'Categorized fire size (e.g., Small, Medium, Large, Extreme)',
    'is_weekend': 'Boolean indicating if the discovery date was a weekend',
    'season': 'Season of the year (Spring, Summer, Fall, Winter)',
    'state_avg_temp': 'Average temperature for the state',
    'state_fire_frequency': 'Number of fires in the state up to that point in the year'
}